account/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from account import views
from django.conf import settings

urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.Login, name='Login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^login/Usertype/$', views.Usertype, name='Usertype'),
]

cadetparent/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from cadetparent import views


urlpatterns = [
    url(r'^cadet_parent_profile/$', views.cadet_parent_profile, name='cadet_parent_profile'),
]

employee/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from employee import views

urlpatterns = [
    url(r'^employee_profile/$', views.employee_profile, name='employee_profile'),
    url(r'^create_student_record/$', views.create_student_record, name='create_student_record'),
    url(r'^student_detail/(?P<pk>\d+)$', views.student_detail, name='student_detail'),
    url(r'^edit_student_record/(?P<pk>\d+)$', views.edit_student_record, name='edit_student_record')

]

exam/urls.py
from django.conf.urls import url
from exam import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^create_exam_record/$', views.create_exam_record, name='create_exam_record'),
    url(r'^save_exam_records/$', views.save_exam_records, name='save_exam_records'),
    url(r'^student_exam_edit/(?P<pk>\d+)$', views.student_exam_edit, name='student_exam_edit'),
]

maintainexam/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(('exam.urls'), namespace='exam')),
    url(r'', include(('account.urls'), namespace='accountregistrations')),
    url(r'', include(('employee.urls'), namespace='employee')),
    url(r'', include(('cadetparent.urls'), namespace='cadetparent')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/forms.py
from django import forms
from exam.models import Teacher, Student_Exam_Record, Mid_Term_Exam_Record_Junior, Mid_Term_Exam_Record_Senior
from django.core.exceptions import ValidationError
from django.forms import BaseInlineFormSet


class DateInput(forms.DateInput):
    input_type = 'date'


class ExamRecordForm1(forms.Form):
    CLASS_CHOICES = (
        [(str(i), str(i)) for i in range(6, 13)]
    )
    SECTION_CHOICE = (
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('E', 'E'),
        ('F', 'F'),
    )
    EXAM_CHOICES = (
        ('Periodic Test 1', 'Periodic Test 1'),
        ('Mid Term Exam', 'Mid Term Exam'),
        ('Periodic Test 2 ', 'Periodic Test 2'),
        ('Pre Mid Term Examination', 'Pre Mid Term Examination'),
        ('Post Mid Term Examination', 'Post Mid Term Examination'),
    )
    SUBJECT_CHOICES = (
        ('English', 'English'),
        ('Hindi', 'Hindi'),
        ('Tamil', 'Tamil'),
        ('Maths', 'Maths'),
        ('General Science', 'General Science'),
        ('Social Science', 'Social Science'),
        ('Computer Application-I', 'Computer Application-I'), ('Computer Application-II', 'Computer Application-II'),
        ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'),
        ('Computer', 'Computer')
    )
    Select_Class = forms.ChoiceField(choices=CLASS_CHOICES, required=True)
    Section = forms.ChoiceField(choices=SECTION_CHOICE, required=True)
    Exam = forms.ChoiceField(choices=EXAM_CHOICES, required=True)
    Subject = forms.ChoiceField(choices=SUBJECT_CHOICES, required=True)
    Max_Marks = forms.IntegerField(required=True)
    Exam_Date = forms.DateField(widget=DateInput(), required=True)
    Class_Teacher = forms.ChoiceField(required=True)

    def __init__(self, *args, **kwargs):
        super(ExamRecordForm1, self).__init__(*args, **kwargs)

        self.fields['Class_Teacher'] = forms.ChoiceField(
            choices=[(teacher.Teacher_Name, teacher.Teacher_Name) for teacher in
                     Teacher.objects.all().order_by('Teacher_Name')]
        )


class ExamRecordForm2(forms.Form):
    Marks = forms.IntegerField(required=True)
    Grade = forms.CharField(max_length=3)
    Percentage = forms.DecimalField(max_digits=5,decimal_places=2,required=True)
    Rank = forms.IntegerField(required=False)
    Max_marks = forms.DecimalField(widget=forms.HiddenInput(),max_digits=5, decimal_places=2)

    def clean(self):
        if self.cleaned_data['Marks'] > self.cleaned_data['Max_marks']:
            raise ValidationError(
                "{} is invalid, must be less than or equal to Max_Marks {}".format(self.cleaned_data['Marks'],
                                                                                   self.cleaned_data['Max_marks']))


class StudentExamEditForm(forms.ModelForm):
    Exam_Date = forms.DateField(widget=DateInput())

    class Meta:
        model = Student_Exam_Record
        fields = '__all__'
        exclude = ['Student']

    def clean(self):
        # print("clean")
        if self.cleaned_data['Marks'] > self.cleaned_data['Max_Marks']:
            raise ValidationError(
                "{} is invalid, must be less than or equal to Max_Marks {}".format(self.cleaned_data['Marks'],
                                                                                   self.cleaned_data['Max_Marks']))


class MidTermExamEditFormJunior(forms.ModelForm):
    Exam_Date = forms.DateField(widget=DateInput())

    class Meta:
        model = Mid_Term_Exam_Record_Junior
        fields = '__all__'
        exclude = ['Student']

    def clean(self):
        # print("clean")
        if self.cleaned_data['Theory_Exam_Marks'] > 80.00 or self.cleaned_data['NBS_Marks'] > 5.00 or self.cleaned_data[
            'PT1_Exam_Marks'] > 5.00 or self.cleaned_data['SEA_Marks'] > 5.00 or self.cleaned_data['Percentage'] > 100.00:
            raise ValidationError(
                "Input Marks is invalid, must be less than or equal to Max_Marks")


class MidTermExamEditFormSenior(forms.ModelForm):
    Exam_Date = forms.DateField(widget=DateInput())

    class Meta:
        model = Mid_Term_Exam_Record_Senior
        fields = '__all__'
        exclude = ['Student']

    def clean(self):
        # print("clean")
        if self.cleaned_data['Theory_Marks'] > 70.00 or self.cleaned_data['Practical_Marks'] > 30.00 or self.cleaned_data['Percentage'] > 100.00:
            raise ValidationError(
                "Input Marks is invalid, must be less than or equal to Max_Marks")

# class StudentExamFormSet(BaseInlineFormSet):
#     def clean(self):
#         super().clean()
#         for form in self.forms:
#             print("clean")
#             if form.cleaned_data['Marks'] > form.cleaned_data['Max_marks']:
#                 raise ValidationError(
#                     "{} is invalid, must be less than or equal Max_Marks {}".format(form.cleaned_data['Marks'],
#                                                                                     form.cleaned_data['Max_marks']))

exam/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ExamRecordForm1, ExamRecordForm2, StudentExamEditForm, DateInput, MidTermExamEditFormJunior, MidTermExamEditFormSenior
from employee.models import StudentProfile
from .models import Student_Exam_Record, Mid_Term_Exam_Record_Senior, Mid_Term_Exam_Record_Junior
from django.forms import formset_factory, inlineformset_factory
from maintainexam.decorators import user_is_employee
from django.contrib import messages
import datetime, urllib.parse


# Create your views here.

def home(request):
    return render(request, 'exam/index.html', {'len': range(4)})


@user_is_employee
def create_exam_record(request):
    print("Create Student Record")

    if request.method == "POST" and 'form1' in request.POST:
        record_form = ExamRecordForm1(request.POST or None, request.FILES or None)
        if record_form.is_valid():
            print("Successfully Saved")
            return HttpResponseRedirect("/save_exam_records/?%s" % urllib.parse.urlencode(record_form.cleaned_data))

    else:
        record_form = ExamRecordForm1()

    context = {'record_form': record_form, }
    return render(request, 'exam/create_exam_record.html', context)


@user_is_employee
def save_exam_records(request):
    print("data")
    data = request.GET
    if data['Subject'] == 'Hindi' or data['Subject'] == 'Tamil' or data['Subject'] == 'CS' or data[
        'Subject'] == 'Biology':
        students = StudentProfile.objects.filter(Class=data['Select_Class'], Section=data['Section'],
                                                 Elective_Subject=data['Subject']).order_by('Roll_Num')
    else:
        students = StudentProfile.objects.filter(Class=data['Select_Class'], Section=data['Section']).order_by(
            'Roll_Num')

    ExamRecordFormSet1 = formset_factory(ExamRecordForm2, extra=students.count())
    ExamRecordFormSet2 = inlineformset_factory(StudentProfile, Mid_Term_Exam_Record_Junior, fields=(
        'Theory_Exam_Marks', 'NBS_Marks', 'SEA_Marks', 'PT1_Exam_Marks', 'Grade', 'Percentage', 'Rank'))
    ExamRecordFormSet3 = inlineformset_factory(StudentProfile, Mid_Term_Exam_Record_Senior,
                                               fields=('Theory_Marks', 'Practical_Marks', 'Percentage', 'Rank'))

    if request.method == "POST" and 'form2' in request.POST:

        if 6 <= int(data['Select_Class']) <= 10 and data['Exam'] == 'Mid Term Exam' or 6 <= int(
                data['Select_Class']) <= 10 and data['Exam'] == 'Post Mid Term Examination':
            formset = ExamRecordFormSet2(request.POST or None, prefix='formset2')
        elif 11 <= int(data['Select_Class']) <= 12 and data['Exam'] == 'Mid Term Exam' or 11 <= int(
                data['Select_Class']) <= 12 and data['Exam'] == 'Post Mid Term Examination':
            formset = ExamRecordFormSet3(request.POST or None, prefix='formset3')
        else:
            formset = ExamRecordFormSet1(request.POST or None, prefix='formset1')
        print('post')
        if formset.is_valid():
            combine = zip(students, formset)
            if formset.prefix == 'formset1':
                for student, form in combine:
                    print('valid')
                    student_exam_record = Student_Exam_Record.objects.create(Student=student,
                                                                             Exam=data['Exam'],
                                                                             Exam_Date=data['Exam_Date'],
                                                                             Subject=data['Subject'],
                                                                             Grade=form.cleaned_data['Grade'],
                                                                             Marks=form.cleaned_data['Marks'],
                                                                             Rank=form.cleaned_data['Rank'],
                                                                             Max_Marks=data['Max_Marks'],
                                                                             Class_Teacher=data['Class_Teacher'])
                    student_exam_record.save()

            if formset.prefix == 'formset2':
                for student, form in combine:
                    student_exam_record = Mid_Term_Exam_Record_Junior.objects.create(Student=student,
                                                                                     Exam=data['Exam'],
                                                                                     Exam_Date=data['Exam_Date'],
                                                                                     Subject=data['Subject'],
                                                                                     Theory_Exam_Marks=
                                                                                     form.cleaned_data[
                                                                                         'Theory_Exam_Marks'],
                                                                                     NBS_Marks=form.cleaned_data[
                                                                                         'NBS_Marks'],
                                                                                     SEA_Marks=form.cleaned_data[
                                                                                         'SEA_Marks'],
                                                                                     PT1_Exam_Marks=form.cleaned_data[
                                                                                         'PT1_Exam_Marks'],
                                                                                     Percentage=form.cleaned_data[
                                                                                         'Percentage'],
                                                                                     Grade=form.cleaned_data['Grade'],
                                                                                     Rank=form.cleaned_data['Rank'],
                                                                                     )

                    student_exam_record.save()

            if formset.prefix == 'formset3':
                for student, form in combine:
                    print('valid3')
                    student_exam_record = Mid_Term_Exam_Record_Senior.objects.create(Student=student,
                                                                                     Exam=data['Exam'],
                                                                                     Exam_Date=data['Exam_Date'],
                                                                                     Subject=data['Subject'],
                                                                                     Percentage=form.cleaned_data[
                                                                                         'Percentage'],
                                                                                     Theory_Marks=form.cleaned_data[
                                                                                         'Theory_Marks'],
                                                                                     Practical_Marks=form.cleaned_data[
                                                                                         'Practical_Marks'],
                                                                                     Rank=form.cleaned_data['Rank'],
                                                                                     )
                    student_exam_record.save()

                    print("Successfully Saved again")
            return redirect('employee:employee_profile')
        else:
            print(formset.errors)
    else:

        if 6 <= int(data['Select_Class']) <= 10 and data['Exam'] == 'Mid Term Exam' or 6 <= int(
                data['Select_Class']) <= 10 and \
                data['Exam'] == 'Post Mid Term Examination':
            formset = ExamRecordFormSet2(prefix='formset2')
        elif 11 <= int(data['Select_Class']) <= 12 and data['Exam'] == 'Mid Term Exam' or 11 <= int(
                data['Select_Class']) <= 12 and data[
            'Exam'] == 'Post Mid Term Examination':
            formset = ExamRecordFormSet3(prefix='formset3')
        else:
            formset = ExamRecordFormSet1(prefix='formset1')

    combine = zip(students, formset)
    context = {

        'Max_marks': data['Max_Marks'],
        'formset': formset,
        'combine': combine,

    }
    return render(request, 'exam/save_exam_record.html', context)

@user_is_employee
def student_exam_edit(request, pk):
    student_profile = StudentProfile.objects.get(pk=pk)

    exam_record1 = Student_Exam_Record.objects.filter(Student=student_profile, Exam='Periodic Test 1').order_by(
        'Subject')
    exam_record3 = Student_Exam_Record.objects.filter(Student=student_profile,
                                                      Exam='Periodic Test 2').order_by('Subject')
    exam_record4 = Student_Exam_Record.objects.filter(Student=student_profile,
                                                      Exam='Pre Mid Term Examination').order_by('Subject')

    if 6 <= int(student_profile.Class) <= 10:

        exam_record2 = Mid_Term_Exam_Record_Junior.objects.filter(Student=student_profile,
                                                                  Exam='Mid Term Exam').order_by('Subject')

        exam_record5 = Mid_Term_Exam_Record_Junior.objects.filter(Student=student_profile,
                                                                  Exam='Post Mid Term Examination').order_by('Subject')
    else:

exam/templates/exam/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SSA Exam Cell</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Unicat project">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/main_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/responsive.css' %}">


</head>
<body>

<div class="super_container">

    {% block content %}
    {% endblock content %}

</div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static  'plugins/greensock/TweenMax.min.js'%}"></script>
<script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js'%}"></script>
<script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

exam/templates/exam/create_exam_record.html
{% extends 'exam/base.html' %}
{% block content %}
    <style>
        input {
            float: right !important;
            min-width: 45%;
        }

        select {
            float: right !important;
            min-width: 45%;
        }

        textarea {
            float: right;
            max-height: 45px;
        }

        p {
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .btn-dark {
            color: #fff;
            background: #14bdee;
            border-color: aqua;
        }

        .errorlist {
            color: red;
        }

    </style>
    {% include 'exam/header.html' %}
    <br>
    <br>
    <div class="container" style="margin-top: 10% !important;">
        <div class="row" style="text-align: center">
            <div class="col-md-12">
                <h1>
                    Add Exam Record
                </h1>
            </div>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <span style="color: red;margin-right: 5px;">*</span><h6>(Required)</h6>
            <div class="col-md-8 col-12">
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                    {% for field in record_form %}
                        <p style="margin-top: 50px; margin-bottom: 50px;">
                            {{field.label}} {% if field.field.required %} <span style="color: red">*</span> {% endif %}
                            {{ field }}
                            {{ field.errors }}
                        </p>
                    {% endfor %}
                    <br>
                    <p align="center">
                        <button class="btn btn-dark" type="submit" name="form1">Save</button>
                    </p>
                </form>
            </div>
            <hr>
        </div>
    </div>
    <br>
    <br>

    {% include 'exam/footer.html' %}
{% endblock content %}

exam/templates/exam/footer.html
{% load static %}
<!-- Footer -->

<footer class="footer">
    <div class="footer_background" style="background-image:url(../../static/images/footer_background.png)"></div>
    <div class="container">
        <div class="row footer_row">
            <div class="col">
                <div class="footer_content">
                    <div class="row">

                        <div class="col-lg-6 footer_col">

                            <!-- Footer About -->
                            <div class="footer_section footer_about">
                                <div class="footer_logo_container">
                                    <a href="#">
                                        <div class="footer_logo_text">SS<span>A</span></div>
                                    </a>
                                </div>
{#                                <div class="footer_about_text">#}
{#                                    <p>Lorem ipsum dolor sit ametium, consectetur adipiscing elit.</p>#}
{#                                </div>#}

                            </div>

                        </div>

                        <div class="col-lg-6 footer_col">
                            <!-- Footer Contact -->
                            <div class="footer_section footer_contact" style="text-align: right;">
                                <div class="footer_title">Contact Us</div>
                                <div class="footer_contact_info">
                                    <ul>
                                        <li>Email:mailtosainik@gmail.com</li>
                                        <li>Phone: 04252 256246</li>
                                        <li>Sainik School Amaravathinagar</li>
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row copyright_row">
            <div class="col">
                <div class="copyright d-flex flex-lg-row flex-column align-items-center justify-content-start">
                    <div class="cr_text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                        All rights reserved | This template is made with <i class="fa fa-heart-o"
                                                                            aria-hidden="true"></i> by <a
                            href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
                    <div class="ml-lg-auto cr_links">
                        <ul class="cr_list">
                            <li><a href="#">Copyright notification</a></li>
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

exam/templates/exam/header.html
<!-- Header -->

<header class="header">

    <!-- Top Bar -->
    <div class="top_bar">
        <div class="top_bar_container">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="top_bar_content d-flex flex-row align-items-center justify-content-start">
                            <ul class="top_bar_contact_list">
                                <li>
                                    <div class="question">Have any questions?</div>
                                </li>
                                <li>
                                    <i class="fa fa-phone" aria-hidden="true"></i>
                                    <div>04252 256246</div>
                                </li>
                                <li>
                                    <i class="fa fa-envelope-o" aria-hidden="true"></i>
                                    <div>mailtosainik@gmail.com</div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Header Content -->
    <div class="header_container">
        <div class="container">
            <div class="row">
                <div class="col-12">


                    <nav class="navbar navbar-expand-sm ">
                        <a href="#">
                            <div class="logo_text">SS<span>A</span></div>
                        </a>
                        <ul class="navbar-nav ml-auto">
                            <li class="active"><a class="nav-link question " style="color: black" href="{% url 'exam:home' %}">Home</a></li>
                            {% if user.is_authenticated %}
                                {% if user.Employee.is_employee %}
                                    <li class="nav-item question"><a class="nav-link"  style="color: black"
                                                            href="{% url 'employee:employee_profile' %}">Profile</a>
                                    </li>
                                {% endif %}
                                {% if user.CadetParent.is_cadet_parent %}
                                    <li class="nav-item question "><a class="nav-link" style="color: black"
                                                            href="{% url 'cadetparent:cadet_parent_profile' %}">Profile</a>
                                    </li>
                                {% endif %}
                            {% endif %}
                            {% if user.is_authenticated %}

                                <li class="nav-item question"><a class="nav-link" style="color: black" href="{% url 'accountregistrations:logout' %}">Logout</a>
                                </li>

                            {% else %}

                                <li class="nav-item question"><a class="nav-link" style="color: black" href="{% url 'accountregistrations:Login' %}">Register
                                    or Login</a></li>

                            {% endif %}
                        </ul>
                    </nav>


                </div>
            </div>
        </div>
    </div>


</header>

exam/templates/exam/index.html
{% extends 'exam/base.html' %}
{% load staticfiles %}
{% block content %}
    {% include 'exam/header.html' %}
    <!-- Home -->
    <div class="home">
        <div class="home_slider_container">
            <!-- Home Slider -->
            <div class="owl-carousel owl-theme home_slider">
                {% for i in len %}
                    <!-- Home Slider Item -->
                    <div class="owl-item">
                        {% if i == 0 %}
                            <div class="home_slider_background"
                                 style="background-image:url({% static "images/home_slider_default_0.jpg" %})"></div>
                        {% endif %}
                        {% if i == 1 %}
                            <div class="home_slider_background"
                                 style="background-image:url({% static "images/home_slider_default_1.jpg" %})"></div>
                        {% endif %}
                        {% if i == 2 %}
                            <div class="home_slider_background"
                                 style="background-image:url({% static "images/home_slider_default_2.jpg" %})"></div>
                        {% endif %}
                        {% if i == 3 %}
                            <div class="home_slider_background"
                                 style="background-image:url({% static "images/home_slider_default_3.jpg" %})"></div>
                        {% endif %}
                        <div class="home_slider_content">
                            <div class="container">
                                <div class="row">
                                    <div class="col text-center">
                                        <div class="home_slider_form_container">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <!-- Home Slider Nav -->

        <div class="home_slider_nav home_slider_prev"><i class="fa fa-angle-left" aria-hidden="true"></i></div>
        <div class="home_slider_nav home_slider_next"><i class="fa fa-angle-right" aria-hidden="true"></i></div>
    </div>




    {% include 'exam/footer.html' %}

{% endblock %}