employee/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from employee import views

urlpatterns = [
    url(r'^employee_profile/$', views.employee_profile, name='employee_profile'),
    url(r'^create_student_record/$', views.create_student_record, name='create_student_record'),
    url(r'^student_detail/(?P<pk>\d+)$', views.student_detail, name='student_detail'),
    url(r'^edit_student_record/(?P<pk>\d+)$', views.edit_student_record, name='edit_student_record')

]

exam/urls.py
from django.conf.urls import url
from exam import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^create_exam_record/$', views.create_exam_record, name='create_exam_record'),
    url(r'^save_exam_records/$', views.save_exam_records, name='save_exam_records'),
    url(r'^student_exam_edit/(?P<pk>\d+)$', views.student_exam_edit, name='student_exam_edit'),
]

maintainexam/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(('exam.urls'), namespace='exam')),
    url(r'', include(('account.urls'), namespace='accountregistrations')),
    url(r'', include(('employee.urls'), namespace='employee')),
    url(r'', include(('cadetparent.urls'), namespace='cadetparent')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django_currentuser.middleware import (
    get_current_user, get_current_authenticated_user)

# Create your models here.
from maintainexam.settings import TIME_ZONE


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="Employee")
    is_employee = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)


class StudentProfile(models.Model):
    CLASS_CHOICE = (
        [(str(i), str(i)) for i in range(6, 13)]
    )
    SECTION_CHOICE = (
        ('A', 'A'),
        ('B', 'B'),
        ('C', 'C'),
        ('D', 'D'),
        ('E', 'E'),
        ('F', 'F'),
    )
    HOUSE_CHOICE = (
        ('Chera Junior', 'Chera Junior'), ('Chola Junior', 'Chola Junior'),
        ('Pandya Junior', 'Pandya Junior'), ('Pallava Junior', 'Pallava Junior'),
        ('Pandya Senior', 'Pandya Senior'),('Chera Senior', 'Chera Senior'),
        ('Chola Senior', 'Chola Senior'), ('Pallava Senior', 'Pallava Senior'),
        ('Bharati', 'Bharati'), ('Velluvar', 'Velluvar'),

    )
    lIISubject = (
        ('Tamil', 'Tamil'), ('Hindi', 'Hindi'), ('Biology', 'Biology'), ('CS', 'CS'),
    )
    Roll_Num = models.IntegerField(unique=True)
    Cadet_Name = models.CharField(max_length=250)
    Class = models.CharField(max_length=2, choices=CLASS_CHOICE, default="--select--")
    Section = models.CharField(max_length=1, choices=SECTION_CHOICE, default="--select--")
    House = models.CharField(max_length=12, choices=HOUSE_CHOICE, default="--select--")
    Aadhar_Num = models.IntegerField()
    EMIS_Num = models.IntegerField()
    Date_Of_Birth = models.DateField()
    Domicile = models.CharField(max_length=250)
    Father_Name = models.CharField(max_length=250)
    Mobile_Num = models.IntegerField()
    Additional_Contact_Num_1 = models.IntegerField(blank=True, null=True)
    Additional_Contact_Num_2 = models.IntegerField(blank=True, null=True)
    Mother_Name = models.CharField(max_length=250)
    Class_Of_Admission = models.CharField(max_length=250)
    Address = models.TextField()
    Father_Occupation = models.CharField(max_length=250)
    Monthly_Income = models.IntegerField()
    Category = models.CharField(max_length=250)
    Background = models.CharField(max_length=250, blank=True, null=True)
    Community = models.CharField(max_length=250, blank=True, null=True)
    Caste = models.TextField()
    Identification_Mark = models.TextField(blank=True, null=True)
    School_Last_Studied = models.CharField(max_length=350)
    Date_Of_Arrival = models.DateField()
    TC_No_Last_Studied = models.CharField(max_length=550, blank=True, null=True)
    TC_No_Issued_Date = models.DateField(blank=True, null=True)
    Date_Of_Withdrawal = models.DateField(blank=True, null=True)
    TC_No_Sainik_School = models.CharField(max_length=550, blank=True, null=True)
    # To-do
    Date = models.DateField(blank=True, null=True)
    Remark = models.TextField(blank=True, null=True)
    Total_Num_of_sister = models.IntegerField(blank=True, null=True)
    Total_Num_of_Brother = models.IntegerField(blank=True, null=True)
    # To-do
    Photograph_Cadet = models.ImageField(
        null=True, blank=True,
        height_field="height_field",
        width_field="width_field")
    height_field = models.IntegerField(default=None, blank=True, null=True)
    width_field = models.IntegerField(default=None, blank=True, null=True)
    NDA_Qaulified = models.CharField(max_length=250, default=None, blank=True, null=True)
    NDA_All_India_Rank = models.IntegerField(default=None, blank=True, null=True)
    Elective_Subject = models.CharField(max_length=12, choices=lIISubject, null=True, blank=True)


    def __str__(self):
        return str(self.Roll_Num)

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in StudentProfile._meta.fields]


class StudentEditLog(models.Model):
    employee_id = models.ForeignKey(Employee, on_delete=models.DO_NOTHING)
    student_profile_id = models.ForeignKey(StudentProfile, on_delete=models.DO_NOTHING)
    timestamp = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return str(self.employee_id.user)
        # + ', ' + str(self.student_profile_id) + ', ' + str(self.timestamp.date()) + ', ' + str(self.timestamp.time())

    @receiver(post_save, sender=StudentProfile)
    def create_EditLog(sender, instance, created, **kwargs):
        user = Employee.objects.get(user_id=get_current_authenticated_user().id)
        StudentEditLog.objects.create(employee_id=user, student_profile_id=instance)

    post_save.connect(create_EditLog, sender=StudentProfile)

employee/forms.py
from django import forms
from employee.models import StudentProfile

class DateInput(forms.DateInput):
    input_type = 'date'


class StudentProfileAddForm(forms.ModelForm):
    class Meta:
        model = StudentProfile
        fields = '__all__'
        widgets = {
            'Date_Of_Birth': DateInput(),
            'Date_Of_Arrival': DateInput(),
            'Date_Of_Withdrawal' : DateInput(),
            'Date': DateInput(),
            'TC_No_Issued_Date': DateInput()
        }

employee/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from employee.models import StudentProfile, StudentEditLog, Employee
from employee.forms import StudentProfileAddForm
from maintainexam.decorators import user_is_employee
from exam.models import Student_Exam_Record, Mid_Term_Exam_Record_Senior, Mid_Term_Exam_Record_Junior
from django.db.models import Q
from django.contrib.auth.models import User



# Create your views here.
@user_is_employee
def employee_profile(request):
    students = StudentProfile.objects.all()
    query = request.GET.get("q")

    if query:
        students = students.filter(Q(Roll_Num__icontains=query) |
                                             Q(Cadet_Name__icontains=query) |
                                             Q(Class__icontains=query) |
                                             Q(House__icontains=query)
                                             ).distinct().order_by('Cadet_Name')
    # else:
    #     students = StudentProfile.objects.none()
    # for larger inputs
    context = {

        'student_profile': students
    }
    # print("Request User", request.user.id)
    # user = Employee.objects.get(user_id=request.user.id)
    # print("User", user)
    return render(request, 'employee/employee_profile.html', context)


@user_is_employee
def create_student_record(request):
    print("Create Student Record")
    if request.method == "POST":
        add_form = StudentProfileAddForm(request.POST or None, request.FILES or None)
        if add_form.is_valid():
            instance = add_form.save(commit=False)
            instance.save()
            # user = Employee.objects.get(user_id=request.user.id)
            # print("instance", instance.pk)
            # student_profile = StudentProfile.objects.get(id=instance.pk)
            # print("User", user)
            # print("Student Profile Id", instance.pk)
            # StudentEditLog.objects.create(employee_id=user, student_profile_id=student_profile)

            print("Successfully Saved")
            return redirect('employee:employee_profile')
        else:
            arr = []
            for field in add_form:
                arr.append(field.errors)
            messages.error(request, add_form.errors)
            add_form = StudentProfileAddForm(request.POST or None, request.FILES or None)
    else:
        add_form = StudentProfileAddForm()

    context = {
        'add_form': add_form
    }
    return render(request, 'employee/create_student_record.html', context)


@user_is_employee
def student_detail(request, pk):
    student_profile = get_object_or_404(StudentProfile, id=pk)
    exam_record1 = Student_Exam_Record.objects.filter(Student=student_profile, Exam='Periodic Test 1').order_by('Subject')
    exam_record3 = Student_Exam_Record.objects.filter(Student=student_profile,
                                                      Exam='Periodic Test 2').order_by('Subject')
    exam_record4 = Student_Exam_Record.objects.filter(Student=student_profile,
                                                      Exam='Pre Mid Term Examination').order_by('Subject')
    print(int(student_profile.Class))
    if 6 <= int(student_profile.Class) <= 10:
        print(int(student_profile.Class))
        exam_record2 = Mid_Term_Exam_Record_Junior.objects.filter(Student=student_profile, Exam='Mid Term Exam').order_by('Subject')
        print(exam_record2,"asd")
        exam_record5 = Mid_Term_Exam_Record_Junior.objects.filter(Student=student_profile, Exam='Post Mid Term Examination').order_by('Subject')
    else:
        exam_record2 = Mid_Term_Exam_Record_Senior.objects.filter(Student=student_profile,
                                                                  Exam='Mid Term Exam').order_by('Subject')
        exam_record5 = Mid_Term_Exam_Record_Senior.objects.filter(Student=student_profile,
                                                                  Exam='Post Mid Term Examination').order_by('Subject')

    print(exam_record2)
    context={
        'student_profile': student_profile,
        'examrecord1': exam_record1,
        'examrecord2': exam_record2,
        'examrecord3': exam_record3,
        'examrecord4': exam_record4,
        'examrecord5': exam_record5,
    }

    return render(request, 'employee/student_detail.html', context)


@user_is_employee
def edit_student_record(request, pk):
    student_profile = get_object_or_404(StudentProfile, id=pk)

    if request.method == "POST":
        add_form = StudentProfileAddForm(request.POST or None, request.FILES or None, instance=student_profile)
        if add_form.is_valid() == True:
            instance = add_form.save(commit=False)
            instance.save()
            print(instance)
            # user = Employee.objects.get(user_id=request.user.id)
            # print("instance", instance.pk)
            # student_profile = StudentProfile.objects.get(id=instance.pk)
            # print("User", user)
            # print("Student Profile Id", instance.pk)
            # StudentEditLog.objects.create(employee_id=user, student_profile_id=student_profile)
            print("Successfully Saved")
            return redirect('employee:employee_profile')
        else:
            arr = []
            for field in add_form:
                arr.append(field.errors)
            messages.error(request, add_form.errors)

    else:
        add_form = StudentProfileAddForm(request.POST or None, request.FILES or None, instance=student_profile)

    context = {
        'add_form': add_form
    }
    return render(request, 'employee/create_student_record.html', context)

employee/templates/employee/create_student_record.html
{% extends 'exam/base.html' %}
{% block content %}
    <style>
        input {
            float: right !important;
            min-width: 45%;
        }

        select {
            float: right !important;
            min-width: 45%;
        }

        textarea {
            float: right;
            max-height: 45px;
        }

        p {
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .btn-dark {
            color: #fff;
            background: #14bdee;
            border-color: aqua;
        }

        .errorlist {
            color: red;
        }

    </style>
    {% include 'exam/header.html' %}
    <br>
    <br>
    <div class="container" style="margin-top: 10% !important;">
        <div class="row" style="text-align: center">
            <div class="col-md-12">
                <h1>
                    Add Cadet Record
                </h1>
            </div>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 col-12">
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                    {% for field in add_form %}
                        <p style="margin-top: 50px; margin-bottom: 50px;">
                            {{ field.label }} {% if field.field.required %}
                            <span style="color: red">*</span> {% endif %}
                            {{ field }}
                            {{ field.errors }}
                        </p>
                    {% endfor %}
                    <br>
                    <p align="center">
                        <button class="btn btn-dark" type="submit">Save</button>
                    </p>
                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
    <br>
    <br>

    {% include 'exam/footer.html' %}
{% endblock content %}

employee/templates/employee/employee_profile.html
{% extends 'exam/base.html' %}
{% block content %}
    <style>
        .btn-dark {
            color: #fff;
            background: #14bdee;
            border-color: aqua;
        }
    </style>
    {% include 'exam/header.html' %}
    <div class="container" style="margin-top: 15% !important;">
        <div class="row">
            <div class="col-md-4 col-xs-12" style="text-align: center">
                <a href="{% url 'employee:create_student_record' %}">
                    <button class="btn btn-dark" href="">
                        Add Student Record
                    </button>
                </a>
            </div>
            <div class="col-md-4 col-xs-12" style="text-align: center">
                <a href="{% url 'exam:create_exam_record' %}">
                    <button class="btn btn-dark" href="">
                        Add Exam Record
                    </button>
                </a>
            </div>

            <div class="col-md-4 col-xs-12">
                <form method="GET" action="" style="width: unset!important; float: right">
                    <input type="text" name="q" class="textbox" placeholder="Search...."
                           value="{{ request.GET.q }}">
                    <input title="Search" value="Search" type="submit" class="button">
                </form>
            </div>

            <hr>

        </div>
    </div>
    <br>
    <br>
    <div class="container">
        <div class="row">
            {% for profile in student_profile %}
                <div class="col-md-3 col-12" style="text-align: center; margin-top: 15px !important;">
                    <a href="{% url 'employee:student_detail' pk=profile.id %}">
                        <div class="img-thumbnail img-fluid">
                            <img src="{% if profile.Photograph_Cadet %}{{ profile.Photograph_Cadet.url }}{% endif %}"
                                 class="rounded img-fluid"
                                 alt="Cadet Photo" style="max-height: 250px!important; min-height: 250px!important;">
                            <h2>{{ profile.Roll_Num }}</h2>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>


    </div>
    <br>
    <br>
    <hr>
    {% include 'exam/footer.html' %}
{% endblock content %}